# Generated by Django 4.2.7 on 2023-12-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_userbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='user',
            new_name='user_id',
        ),
    ]
