# Generated by Django 4.2.7 on 2023-12-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_rename_book_userbook_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='userbook',
            old_name='user_id',
            new_name='user',
        ),
    ]
