# Generated by Django 4.2.7 on 2024-01-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_rename_book_id_userbook_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
