# Generated by Django 4.2.7 on 2024-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_userbook_created_at_userbook_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_l',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_m',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_s',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
