# Generated by Django 4.2.7 on 2024-04-30 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookshelf', '0007_rename_first_name_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='liked',
            field=models.ManyToManyField(related_name='users_liked_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LikedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike')], max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_liked', to='bookshelf.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
